AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal EMR cluster for Spark testing.

Parameters:
  ClusterName:
    Type: String
    Default: emr-test-cluster
  ReleaseLabel:
    Type: String
    Default: emr-6.15.0
  LogUri:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  MasterInstanceType:
    Type: String
    Default: m5.xlarge
  CoreInstanceType:
    Type: String
    Default: m5.xlarge
  CoreInstanceCount:
    Type: Number
    Default: 1
  ServiceRole:
    Type: String
    Default: EMR_DefaultRole
  JobFlowRole:
    Type: String
    Default: EMR_EC2_DefaultRole

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: EmrRoleAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/${JobFlowRole}
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${ArtifactBucket}
              - !Sub arn:aws:s3:::${ArtifactBucket}/*

  EmrCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: !Ref ClusterName
      ReleaseLabel: !Ref ReleaseLabel
      Applications:
        - Name: Spark
        - Name: Hadoop
      LogUri: !Ref LogUri
      VisibleToAllUsers: true
      JobFlowRole: !Ref JobFlowRole
      ServiceRole: !Ref ServiceRole
      Instances:
        Ec2SubnetId: !Ref SubnetId
        Ec2KeyName: !Ref KeyName
        KeepJobFlowAliveWhenNoSteps: true
        TerminationProtected: false
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref MasterInstanceType
        CoreInstanceGroup:
          InstanceCount: !Ref CoreInstanceCount
          InstanceType: !Ref CoreInstanceType

Outputs:
  ClusterId:
    Description: EMR cluster ID
    Value: !Ref EmrCluster
  ArtifactBucketName:
    Description: S3 bucket for Spark artifacts and outputs
    Value: !Ref ArtifactBucket